In [3]:
# Import libraries
import numpy as np
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer
# Create feature
feature=np.array([["Texas"],["California"],["Texas"],["Delaware"],["Texas"]])
# Create one-hot encoder
one_hot=LabelBinarizer()
# One-hot encode feature
one_hot.fit_transform(feature)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
one_hot.classes_

array(['California', 'Delaware', 'Texas'], dtype='<U10')

In [5]:
one_hot.inverse_transform(one_hot.transform(feature))

array(['Texas', 'California', 'Texas', 'Delaware', 'Texas'], dtype='<U10')

In [6]:
# Import library
import pandas as pd
# Create dummy variables from feature
pd.get_dummies(feature[:,0])
# Create multiclass feature
multiclass_feature=[("Texas","Florida"),
("California","Alabama"),
("Texas","Florida"),
("Delware","Florida"),
("Texas","Alabama")]
# Create multiclass one-hot encoder
one_hot_multiclass=MultiLabelBinarizer()
# One-hot encode multiclass feature
one_hot_multiclass.fit_transform(multiclass_feature)

array([[0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1]])

In [7]:
# View classes
one_hot_multiclass.classes_

array(['Alabama', 'California', 'Delware', 'Florida', 'Texas'],
      dtype=object)

In [9]:
import pandas as pd
dataframe = pd.DataFrame({"Score" : ["Low","Low","Medium","Medium","High"]})
scale_mapper = { "Low" : 1 , "Medium":2 , "High":3} 
dataframe["Score"].replace(scale_mapper)

0    1
1    1
2    2
3    2
4    3
Name: Score, dtype: int64

In [13]:
dataframe=pd.DataFrame({"Score":["Low",
                                 "Low",
                                 "Medium",
                                 "Medium",
                                 "High",
                                 "Barely More Than Medium"]})
scale_mapper={"Low":1,
              "Medium":2,
              "Barely More Than Medium":3,
              "High":4}

dataframe["Score"].replace(scale_mapper)

0    1
1    1
2    2
3    2
4    4
5    3
Name: Score, dtype: int64

In [14]:
scale_mapper={"Low":1,
              "Medium":2,
              "Barely More Than Medium":2.1,
              "High":3}
dataframe["Score"].replace(scale_mapper)

0    1.0
1    1.0
2    2.0
3    2.0
4    3.0
5    2.1
Name: Score, dtype: float64

In [15]:
# Import library

from sklearn.feature_extraction import DictVectorizer
# Create dictionary

data_dict=[{"Red":2,"Blue":4},
{"Red":4,"Blue":3},
{"Red":1,"Yellow":2},
{"Red":2,"Yellow":2}]
# Create dictionary vectorizer

dictvectorizer=DictVectorizer(sparse=False)
# Convert dictionary to feature matrix

features=dictvectorizer.fit_transform(data_dict)
# View feature matrix

features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

In [16]:
feature_names = dictvectorizer.get_feature_names()
feature_names

C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['Blue', 'Red', 'Yellow']

In [19]:
import pandas as pd 
pd.DataFrame(features,columns = feature_names)

Blue  Red  Yellow
0   4.0  2.0     0.0
1   3.0  4.0     0.0
2   0.0  1.0     2.0
3   0.0  2.0     2.0

In [20]:
# Create word counts dictionaries for four documents
doc_1_word_count={"Red":2,"Blue":4}
doc_2_word_count={"Red":4,"Blue":3}
doc_3_word_count={"Red":1,"Yellow":2}
doc_4_word_count={"Red":2,"Yellow":2}
# Create list
doc_word_counts=[doc_1_word_count,
doc_2_word_count,
doc_3_word_count,
doc_4_word_count]
# Convert list of word count dictionaries into feature matrix
dictvectorizer.fit_transform(doc_word_counts)

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])