In [11]:
#18.1 Training a Classifer for Continous Features
# Load libraries
from sklearn import datasets 
from sklearn.naive_bayes import GaussianNB 

# Load data 
iris = datasets.load_iris()
features = iris.data
target = iris.target 

# Create Gaussian Naive Bayes object 
classifier = GaussianNB()

# Train model 
model = classifier.fit(features, target)




In [12]:
# Create new observation
new_observation = [[4, 4, 4, 0.4]]

# Predict class
model.predict(new_observation)


array([1])

In [13]:
# Create Gaussian Naive Bayes object with prior probabilities of each class
clf = GaussianNB(priors=[0.25, 0.25, 0.5])

# Train model
model = clf.fit(features, target)


In [14]:
#18.2 Training a Classifierfor Discrete and Count Features 
# Load libraries
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
# Create text
text_data=np.array(['I love Brazil. Brazil!','Brazil is best','Germany beats both'])
# Create bag of words
count=CountVectorizer()
bag_of_words=count.fit_transform(text_data)
# Create feature matrix
features=bag_of_words.toarray()
# Create target vector
target=np.array([0,0,1])
# Create multinomial naive Bayes object with prior probabilities of each class
classifer=MultinomialNB(class_prior=[0.25,0.5])
# Train model
model=classifer.fit(features,target)

In [15]:
# Create new observation
new_observation=[[0,0,0,1,0,1,0]]
# Predict new observation's class
model.predict(new_observation)

array([0])

In [16]:
#18.3 Training a Naive BayesClassifierfor Binary Features
# Load libraries
import numpy as np
from sklearn.naive_bayes import BernoulliNB
# Create three binary features
features=np.random.randint(2,size=(100,3))
# Create a binary target vector
target=np.random.randint(2,size=(100,1)).ravel()
# Create Bernoulli Naive Bayes object with prior probabilities of each class
classifer=BernoulliNB(class_prior=[0.25,0.5])
# Train model
model=classifer.fit(features,target)

In [17]:
model_uniform_prior=BernoulliNB(class_prior=None,fit_prior=True)

In [18]:
#18.4 Calibrating Predicted Probabilities
# Load libraries
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.calibration import CalibratedClassifierCV
# Load data
iris=datasets.load_iris()
features=iris.data
target=iris.target
# Create Gaussian Naive Bayes object
classifer=GaussianNB()
# Create calibrated cross-validation with sigmoid calibration
classifer_sigmoid=CalibratedClassifierCV(classifer,cv=2,method='sigmoid')
# Calibrate probabilities
classifer_sigmoid.fit(features,target)
# Create new observation
new_observation=[[2.6,2.6,2.6,0.4]]
# View calibrated probabilities
classifer_sigmoid.predict_proba(new_observation)

array([[0.31859969, 0.63663466, 0.04476565]])

In [19]:
# Train a Gaussian naive Bayes then predict class probabilities
classifer.fit(features,target).predict_proba(new_observation)

array([[2.31548432e-04, 9.99768128e-01, 3.23532277e-07]])

In [20]:
# View calibrated probabilities
classifer_sigmoid.predict_proba(new_observation)

array([[0.31859969, 0.63663466, 0.04476565]])