In [1]:
# Load libraries
from sklearn import datasets
from sklearn.feature_selection import VarianceThreshold
# import some data to play with
iris=datasets.load_iris()
# Create features and target
features=iris.data
target=iris.target
# Create thresholder
thresholder=VarianceThreshold(threshold=.5)
# Create high variance feature matrix
features_high_variance=thresholder.fit_transform(features)
# View high variance feature matrix
features_high_variance[0:3]

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2]])

In [2]:
# View variances
thresholder.fit(features).variances_

array([0.68112222, 0.18871289, 3.09550267, 0.57713289])

In [4]:
# Load library
from sklearn.feature_selection import VarianceThreshold
features=[[0,1,0],
          [0,1,1],
          [0,1,0],
          [0,1,1],
          [1,0,0]]
thresholder=VarianceThreshold(threshold=(.75*(1-.75)))
thresholder.fit_transform(features)

array([[0],
       [1],
       [0],
       [1],
       [0]])

In [9]:
# Load libraries
import pandas as pd
import numpy as np
# Create feature matrix with two highly correlated features
features=np.array([[1,1,1],
                   [2,2,0],
                   [3,3,1],
                   [4,4,0],
                   [5,5,1],
                   [6,6,0],
                   [7,7,1],
                   [8,7,0],
                   [9,7,1]])
# Convert feature matrix into DataFrame
dataframe=pd.DataFrame(features)
# Create correlation matrix
corr_matrix=dataframe.corr().abs()
# Select upper triangle of correlation matrix
upper=corr_matrix.where(np.triu(np.ones(corr_matrix.shape),
k=1).astype(np.bool))
# Find index of feature columns with correlation greater than 0.95
to_drop=[column for column in upper.columns if any(upper[column]>0.95)]
# Drop features
dataframe.drop(dataframe.columns[to_drop],axis=1).head(3)


C:\Users\cduy5\AppData\Local\Temp\ipykernel_6528\907155274.py:20: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  k=1).astype(np.bool))


0  2
0  1  1
1  2  0
2  3  1

In [10]:
dataframe.corr()

0         1         2
0  1.000000  0.976103  0.000000
1  0.976103  1.000000 -0.034503
2  0.000000 -0.034503  1.000000

In [11]:
# Upper triangle of correlation matrix
upper

0         1         2
0 NaN  0.976103  0.000000
1 NaN       NaN  0.034503
2 NaN       NaN       NaN

In [12]:
# Load libraries
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2,f_classif
# Load data
iris=load_iris()
features=iris.data
target=iris.target
# Convert to categorical data by converting data to integers
features=features.astype(int)
# Select two features with highest chi-squared statistics
chi2_selector=SelectKBest(chi2,k=2)
features_kbest=chi2_selector.fit_transform(features,target)
# Show results
print("Original number of features:",features.shape[1])
print("Reduced number of features:",features_kbest.shape[1])


Original number of features: 4
Reduced number of features: 2


In [13]:
# Load library
from sklearn.feature_selection import SelectPercentile
# Select top 75% of features with highest F-values
fvalue_selector=SelectPercentile(f_classif,percentile=75)
features_kbest=fvalue_selector.fit_transform(features,target)
# Show results
print("Original number of features:",features.shape[1])
print("Reduced number of features:",features_kbest.shape[1])


Original number of features: 4
Reduced number of features: 3


In [14]:
# Load libraries
import warnings
from sklearn.datasets import make_regression
from sklearn.feature_selection import RFECV
from sklearn import datasets,linear_model
# Suppress an annoying but harmless warning
warnings.filterwarnings(action="ignore",module="scipy",
message="^internal gelsd")
# Generate features matrix, target vector, and the true coefficients
features,target=make_regression(n_samples=10000,
                                n_features=100,
                                n_informative=2,
                                random_state=1)
# Create a linear regression
ols=linear_model.LinearRegression()
# Recursively eliminate features
rfecv=RFECV(estimator=ols,step=1,scoring="neg_mean_squared_error")
rfecv.fit(features,target)
rfecv.transform(features)

array([[ 0.00850799,  0.7031277 ],
       [-1.07500204,  2.56148527],
       [ 1.37940721, -1.77039484],
       ...,
       [-0.80331656, -1.60648007],
       [ 0.39508844, -1.34564911],
       [-0.55383035,  0.82880112]])

In [15]:
# Number of best features
rfecv.n_features_

2

In [16]:
# Which categories are best
rfecv.support_

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [17]:
# Rank features best (1) to worst
rfecv.ranking_


array([67, 64, 58, 35, 60,  1, 25, 36,  3,  6, 18, 11, 56, 26, 24, 65, 72,
       77, 40, 55, 80, 96, 17, 66, 33, 79, 90, 71, 47,  9, 32, 70, 63, 42,
       53, 88, 76, 50, 54,  1, 46, 38, 81, 78, 29, 95, 69, 31, 48, 74, 85,
       49, 57, 98, 37, 89, 30, 20, 83, 12, 15, 75, 19,  7, 23, 34, 94, 44,
       45, 51, 22, 84, 82,  2, 62, 68, 61, 14, 39, 92,  8, 73, 21, 86, 41,
        4, 10, 52, 99, 97, 27, 16,  5, 87, 13, 59, 43, 91, 93, 28])