In [3]:
#12.1 Selecting Best Models Using Exhaustive Search
# Load libraries
import numpy as np
from sklearn import linear_model,datasets
from sklearn.model_selection import GridSearchCV
# Load data
iris=datasets.load_iris()
features=iris.data
target=iris.target
# Create logistic regression
logistic=linear_model.LogisticRegression()
# Create range of candidate penalty hyperparameter values
penalty=['l1','l2']
# Create range of candidate regularization hyperparameter values
C=np.logspace(0,4,10)
# Create dictionary hyperparameter candidates
hyperparameters=dict(C=C,penalty=penalty)
# Create grid search
gridsearch=GridSearchCV(logistic,hyperparameters,cv=5,verbose=0)
# Fit grid search
best_model=gridsearch.fit(features,target)


C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [4]:
np.logspace(0,4,10)

array([1.00000000e+00, 2.78255940e+00, 7.74263683e+00, 2.15443469e+01,
       5.99484250e+01, 1.66810054e+02, 4.64158883e+02, 1.29154967e+03,
       3.59381366e+03, 1.00000000e+04])

In [5]:
# View best hyperparameters
print('Best Penalty:',best_model.best_estimator_.get_params()['penalty'])
print('Best C:',best_model.best_estimator_.get_params()['C'])

Best Penalty: l2
Best C: 7.742636826811269


In [ ]:
# Predict target vector
best_model.predict(features)

In [8]:
#12.2 Selecting Best Models Using Randomized Search
# Load libraries
from scipy.stats import uniform
from sklearn import linear_model,datasets
from sklearn.model_selection import RandomizedSearchCV
# Load data
iris=datasets.load_iris()
features=iris.data
target=iris.target
# Create logistic regression
logistic=linear_model.LogisticRegression()
# Create range of candidate regularization penalty hyperparameter values
penalty=['l1','l2']
# Create distribution of candidate regularization hyperparameter values
C=uniform(loc=0,scale=4)
# Create hyperparameter options
hyperparameters=dict(C=C,penalty=penalty)
# Create randomized search
randomizedsearch=RandomizedSearchCV(
logistic,hyperparameters,random_state=1,n_iter=100,cv=5,verbose=0,
n_jobs=-1)
# Fit randomized search
best_model=randomizedsearch.fit(features,target)


C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
230 fits failed out of a total of 500.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
230 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 447, in _check_solver
    raise ValueError(
V

In [9]:
# Define a uniform distribution between 0 and 4, sample 10 values
uniform(loc=0,scale=4).rvs(10)

array([0.1242969 , 0.51426131, 2.21262933, 0.08788313, 1.4220975 ,
       3.17686354, 3.82446281, 3.97052349, 3.26873502, 1.85903191])

In [10]:
# View best hyperparameters
print('Best Penalty:',best_model.best_estimator_.get_params()['penalty'])
print('Best C:',best_model.best_estimator_.get_params()['C'])

Best Penalty: l2
Best C: 3.730229437354635


In [11]:
# Predict target vector
best_model.predict(features)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
#12.3 Selecting Best Models from Multiple LearningAlgorithms
# Load libraries
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
# Set random seed
np.random.seed(0)
# Load data
iris=datasets.load_iris()
features=iris.data
target=iris.target
# Create a pipeline
pipe=Pipeline([("classifier",RandomForestClassifier())])
# Create dictionary with candidate learning algorithms and their hyperparameters
search_space=[{"classifier":[LogisticRegression()],
               "classifier__penalty":['l1','l2'],
               "classifier__C":np.logspace(0,4,10)},
              {"classifier":[RandomForestClassifier()],
               "classifier__n_estimators":[10,100,1000],
               "classifier__max_features":[1,2,3]}]
# Create grid search
gridsearch=GridSearchCV(pipe,search_space,cv=5,verbose=0)
# Fit grid search
best_model=gridsearch.fit(features,target)

C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [13]:
# View best model
best_model.best_estimator_.get_params()["classifier"]

LogisticRegression(C=7.742636826811269)

In [14]:
# Predict target vector
best_model.predict(features)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
#12.4 Selecting Best Models when Preprocessing
# Load libraries
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline,FeatureUnion
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
# Set random seed
np.random.seed(0)
# Load data
iris=datasets.load_iris()
features=iris.data
target=iris.target
# Create a preprocessing object that includes StandardScaler features and PCA
preprocess=FeatureUnion([("std",StandardScaler()),("pca",PCA())])
# Create a pipeline
pipe=Pipeline([("preprocess",preprocess),
("classifier",LogisticRegression())])
# Create space of candidate values
search_space=[{"preprocess__pca__n_components":[1,2,3],
"classifier__penalty":["l1","l2"],
"classifier__C":np.logspace(0,4,10)}]
# Create grid search
clf=GridSearchCV(pipe,search_space,cv=5,verbose=0,n_jobs=-1)
# Fit grid search
best_model=clf.fit(features,target)

C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
150 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
150 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalt

In [19]:
# View best model
best_model.best_estimator_.get_params()['preprocess__pca__n_components']


2

In [20]:
#12.5 Speeding Up Model Selection with Parallelization
# Load libraries
import numpy as np
from sklearn import linear_model,datasets
from sklearn.model_selection import GridSearchCV
# Load data
iris=datasets.load_iris()
features=iris.data
target=iris.target
# Create logistic regression
logistic=linear_model.LogisticRegression()
# Create range of candidate regularization penalty hyperparameter values
# Create range of candidate values for C
C=np.logspace(0,4,1000)
# Create hyperparameter options
hyperparameters=dict(C=C,penalty=penalty)
# Create grid search
gridsearch=GridSearchCV(logistic,hyperparameters,cv=5,n_jobs=-1,verbose=1)
# Fit grid search
best_model=gridsearch.fit(features,target)

Fitting 5 folds for each of 2000 candidates, totalling 10000 fits


C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5000 fits failed out of a total of 10000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5000 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 447, in _check_solver
    raise ValueErro

In [22]:
#12.6 Speeding Up Model Selection UsingAlgorithm-SpecificMethods
# Load libraries
from sklearn import linear_model,datasets
# Load data
iris=datasets.load_iris()
features=iris.data
target=iris.target
# Create cross-validated logistic regression
logit=linear_model.LogisticRegressionCV(Cs=100)
# Train model
logit.fit(features,target)


C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

LogisticRegressionCV(Cs=100)

In [24]:
#12.7 Evaluating Performance After Model Selection

import numpy as np
from sklearn import linear_model,datasets
from sklearn.model_selection import GridSearchCV,cross_val_score
# Load data
iris=datasets.load_iris()
features=iris.data
target=iris.target
# Create logistic regression
logistic=linear_model.LogisticRegression()
# Create range of 20 candidate values for C
C=np.logspace(0,4,20)
# Create hyperparameter options
hyperparameters=dict(C=C)
gridsearch=GridSearchCV(logistic,hyperparameters,cv=5,n_jobs=-1,verbose=0)
# Conduct nested cross-validation and outut the average score
cross_val_score(gridsearch,features,target).mean()


C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

0.9800000000000001