In [2]:
#13.1 Fitting a Line# Load libraries

# Load libraries
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
# Load data with only two features
boston=load_boston()
features=boston.data[:,0:2]
target=boston.target
# Create linear regression
regression=LinearRegression()
# Fit the linear regression
model=regression.fit(features,target)

C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [3]:
# View the intercept
model.intercept_

22.485628113468223

In [3]:
# View the feature coefficients
model.coef_


array([-0.35207832,  0.11610909])

In [4]:
# First value in the target vector multiplied by 1000
target[0]*1000

24000.0

In [5]:
# Predict the target value of the first observation, multiplied by 1000
model.predict(features)[0]*1000

24573.366631705547

In [7]:
 #First coefficient multiplied by 1000
model.coef_[0]*1000

-352.07831564026753

In [9]:
#13.2 Handling Interactive Effects
# Load libraries
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures
# Load data with only two features
boston=load_boston()
features=boston.data[:,0:2]
target=boston.target
# Create interaction term
interaction=PolynomialFeatures(
degree=3,include_bias=False,interaction_only=True)
features_interaction=interaction.fit_transform(features)
# Create linear regression
regression=LinearRegression()
# Fit the linear regression
model=regression.fit(features_interaction,target)

C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [10]:
# View the feature values for first observation
features[0]

array([6.32e-03, 1.80e+01])

In [12]:
# Import library
import numpy as np
# For each observation, multiply the values of the first and second feature
interaction_term=np.multiply(features[:,0],features[:,1])
# View interaction term for first observation
interaction_term[0]

0.11376

In [13]:
#13.3 Fitting a Nonlinear Relationship
# Load library
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures
# Load data with one feature
boston=load_boston()
features=boston.data[:,0:1]
target=boston.target
# Create polynomial features x^2 and x^3
polynomial=PolynomialFeatures(degree=3,include_bias=False)
features_polynomial=polynomial.fit_transform(features)
# Create linear regression
regression=LinearRegression()
# Fit the linear regression
model=regression.fit(features_polynomial,target)

C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [14]:
# View first observation
features[0]

array([0.00632])

In [17]:
# View first observation raised to the second power, x^2
features[0]**2

array([3.99424e-05])

In [16]:
# View first observation raised to the third power, x^3
features[0]**3

array([2.52435968e-07])

In [15]:
# View the first observation's values for x, x^2, and x^3
features_polynomial[0]


array([6.32000000e-03, 3.99424000e-05, 2.52435968e-07])

In [18]:
#13.4 Reducing Variance with Regularization
# Load libraries
from sklearn.linear_model import Ridge
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler
# Load data
boston=load_boston()
features=boston.data
target=boston.target
# Standardize features
scaler=StandardScaler()
features_standardized=scaler.fit_transform(features)
# Create ridge regression with an alpha value
regression=Ridge(alpha=0.5)
# Fit the linear regression
model=regression.fit(features_standardized,target)

C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [19]:
# Load library
from sklearn.linear_model import RidgeCV
# Create ridge regression with three alpha values
regr_cv=RidgeCV(alphas=[0.1,1.0,10.0])
# Fit the linear regression
model_cv=regr_cv.fit(features_standardized,target)
# View coefficients
model_cv.coef_

array([-0.91987132,  1.06646104,  0.11738487,  0.68512693, -2.02901013,
        2.68275376,  0.01315848, -3.07733968,  2.59153764, -2.0105579 ,
       -2.05238455,  0.84884839, -3.73066646])

In [20]:
# View alpha
model_cv.alpha_

1.0

In [21]:
#13.5 Reducing Features with Lasso Regression
# Load library
from sklearn.linear_model import Lasso
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler
# Load data
boston=load_boston()
features=boston.data
target=boston.target
# Standardize features
scaler=StandardScaler()
features_standardized=scaler.fit_transform(features)
# Create lasso regression with alpha value
regression=Lasso(alpha=0.5)
# Fit the linear regression
model=regression.fit(features_standardized,target)


C:\Users\cduy5\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [23]:
# View coefficients
model.coef_

array([-0.11526463,  0.        , -0.        ,  0.39707879, -0.        ,
        2.97425861, -0.        , -0.17056942, -0.        , -0.        ,
       -1.59844856,  0.54313871, -3.66614361])

In [22]:
# Create lasso regression with a high alpha
regression_a10=Lasso(alpha=10)
model_a10=regression_a10.fit(features_standardized,target)
model_a10.coef_

array([-0.,  0., -0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0., -0.])